Joeri action logboek -- is eerste werkende versie van action logboek zonder bestaande figma styling so dont hate uwu
JoeriDekker/Project-D pull request #26
Opened 2024-05-24 19:06 UTC by JoeriDekker

# Definition of done checklist
this checklist is to verify if the written feature adheres to the rules

- [ ] The code is bugfree
- [ ] Feature has been manualy tested
- [ ] Tests have passed, test should be written if none-existing
- [ ] Code is neat without unnecessary code and contains clear comments
- [ ] The user interface is created according to the designs
- [ ] Is secure on base levels (hashing, etc.)

2024-05-24 19:16 UTC, Failfan13 commented on client/src/components/logboek/actionlogboek.tsx
> +                    console.log("Action log", log),
forgor remove console.log ofn?

2024-05-24 19:22 UTC, Failfan13 commented on client/src/components/logboek/actionlogboek.tsx
> +                // Map the API response to the ActionLogboekState structure
Chat wat vinden we hiervan ???

2024-05-25 06:26 UTC, nietrenswens requested changes

2024-05-25 06:26 UTC, nietrenswens commented on client/src/components/logboek/actionlogboek.tsx
> +                        <option selected>Selecteer een maand</option>
Verwerk dit middels de lang files

2024-05-25 17:58 UTC, JoeriDekker commented on client/src/components/logboek/actionlogboek.tsx
> +                        <option selected>Selecteer een maand</option>
fixed

2024-05-28 10:47 UTC, nietrenswens approved these changes
Ik mis testen, maar voor nu ok

2024-05-28 10:52 UTC, merged