Feature/waterlevel adjustor
JoeriDekker/Project-D pull request #38
Opened 2024-06-10 23:39 UTC by Failfan13

Added water adjustor for dashboard
+ delay between clicking and water level rising
+ able to remove an add water
- no backend functionality yet
- not tested with available data as it did not exist at testing

2024-06-11 08:25 UTC, JoeriDekker requested changes
overall werkt t idd, alleen is t naar dat hij dan nu natuurlijk de standaard value van 0 NAP pakt. zou je miss het laatste bestaande meting kunnen gebruiken als standaard value? daardoor is de waterlevel visual niet kapot hehe

2024-06-11 11:36 UTC, JoeriDekker commented
en als ik naar logboek page ga is t kapot :(

2024-06-11 12:45 UTC, Failfan13 commented
> overall werkt t idd, alleen is t naar dat hij dan nu natuurlijk de standaard value van 0 NAP pakt. zou je miss het laatste bestaande meting kunnen gebruiken als standaard value? daardoor is de waterlevel visual niet kapot hehe

Ik heb dit opgelost

> en als ik naar logboek page ga is t kapot :(

Skill issue + L + ratio + cap + fake

> en haal die My neighbourhood WEG

NO >: $

2024-06-12 06:45 UTC, nietrenswens requested changes

2024-06-12 06:45 UTC, nietrenswens commented on client/src/App.tsx
> +        // window.location.href = "/login";
Waarom? Niet geauthenticate gebruikers moeten toch naar de login pagina?

2024-06-12 09:49 UTC, merged